version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.optimized
    container_name: nusantara-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: yk-postgres-dev
      DB_PORT: 5432
      DB_NAME: nusantara_construction
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      JWT_SECRET: nusantara_jwt_secret_2024_construction_management_system
      PORT: 5000
      CORS_ORIGIN: https://nusantaragroup.co
    ports:
      - "5000:5000"
    networks:
      - yk-dev-network
    volumes:
      - ./uploads:/app/uploads
      - ./reports:/app/reports
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.optimized
      args:
        - REACT_APP_API_URL=/api
        - NODE_ENV=production
    container_name: nusantara-frontend-prod
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: /api
      REACT_APP_ENV: production
      GENERATE_SOURCEMAP: false
    ports:
      - "8080:3000"
    networks:
      - yk-dev-network
    depends_on:
      - backend

volumes:
  postgres_data_prod:
    driver: local

networks:
  yk-dev-network:
    external: true
    name: app-yk_yk-dev-network
