#!/bin/bash

echo "==========================================="
echo " MANUAL TESTING GUIDE"
echo "==========================================="
echo ""
echo "Backend is having issues with view creation."
echo "Let's test the TRACKING CODE directly via frontend:"
echo ""
echo "STEPS TO TEST:"
echo "=============="
echo ""
echo "1. Open browser: http://localhost:3000"
echo ""
echo "2. Login to the application"
echo ""
echo "3. Go to any project that has RAB items"
echo ""
echo "4. Create a NEW Purchase Order (PO)"
echo "   - Select RAB items"
echo "   - Enter quantity (e.g., 500 from 1000 available)"
echo "   - Fill supplier info"
echo "   - Click 'Simpan' (Save)"
echo ""
echo "5. After PO is created, run this command to check:"
echo ""
echo "   docker exec nusantara-postgres psql -U admin -d nusantara_construction -c \\"
echo "     \"SELECT * FROM rab_purchase_tracking ORDER BY \"createdAt\" DESC LIMIT 5;\""
echo ""
echo "6. CHECK BACKEND LOGS for DEBUG output:"
echo ""
echo "   docker logs nusantara-backend --tail 100 | grep -E 'DEBUG|🔵|🟢|❌'"
echo ""
echo "==========================================="
echo " WHAT TO LOOK FOR:"
echo "==========================================="
echo ""
echo "✓ SUCCESS if you see:"
echo "  - 🔵 DEBUG markers in backend logs"
echo "  - 🟢 'bulkCreate executed successfully'"
echo "  - New record in rab_purchase_tracking table"
echo "  - rabItemId matches your RAB item"
echo "  - poNumber matches your PO"
echo ""
echo "✗ FAILED if:"
echo "  - No DEBUG markers (code not loaded)"
echo "  - No bulkCreate execution"
echo "  - No new tracking record"
echo ""
echo "==========================================="
echo " QUICK CHECK COMMANDS:"
echo "==========================================="
echo ""
echo "# Count total tracking records:"
echo "docker exec nusantara-postgres psql -U admin -d nusantara_construction -t -c \\"
echo "  \"SELECT COUNT(*) FROM rab_purchase_tracking;\""
echo ""
echo "# Show last 3 tracking records:"
echo "docker exec nusantara-postgres psql -U admin -d nusantara_construction -c \\"
echo "  \"SELECT \\\"rabItemId\\\", \\\"poNumber\\\", quantity, \\\"createdAt\\\" FROM rab_purchase_tracking ORDER BY \\\"createdAt\\\" DESC LIMIT 3;\""
echo ""
echo "# Show backend logs with tracking:"
echo "docker logs nusantara-backend --tail 50 | grep -i tracking"
echo ""
echo "==========================================="
echo ""
echo "Current tracking record count:"
docker exec nusantara-postgres psql -U admin -d nusantara_construction -t -c \
  "SELECT COUNT(*) FROM rab_purchase_tracking;"
echo ""
echo "Last tracking record:"
docker exec nusantara-postgres psql -U admin -d nusantara_construction -c \
  "SELECT \"rabItemId\", \"poNumber\", quantity, \"createdAt\" FROM rab_purchase_tracking ORDER BY \"createdAt\" DESC LIMIT 1;"
echo ""
